export const countryCodes = [
  { country: "United States", code: "+1" },
  { country: "United Kingdom", code: "+44" },
  { country: "India", code: "+91" },
  { country: "Canada", code: "+1" },
  { country: "Australia", code: "+61" },
  { country: "Germany", code: "+49" },
  { country: "France", code: "+33" },
  { country: "Italy", code: "+39" },
  { country: "Spain", code: "+34" },
  { country: "Brazil", code: "+55" },
  { country: "Japan", code: "+81" },
  { country: "China", code: "+86" },
  { country: "Russia", code: "+7" },
  { country: "Mexico", code: "+52" },
  { country: "South Korea", code: "+82" },
  { country: "Indonesia", code: "+62" },
  { country: "Turkey", code: "+90" },
  { country: "Saudi Arabia", code: "+966" },
  { country: "South Africa", code: "+27" },
  { country: "Nigeria", code: "+234" },
]
