import type { User, Channel, Message } from "./types"

// Mock users data
export const mockUsers: User[] = [
  {
    id: "user1",
    name: "Emma Watson",
    avatar: "/placeholder.svg?height=40&width=40",
    email: "emma@example.com",
    isOnline: true,
    lastSeen: "Just now",
    lastMessage: "Let me know when you're free to meet",
    lastMessageTime: "10:42 AM",
    unreadCount: 2,
    isChannel: false,
  },
  {
    id: "user2",
    name: "James Rodriguez",
    avatar: "/placeholder.svg?height=40&width=40",
    email: "james@example.com",
    isOnline: false,
    lastSeen: "5 hours ago",
    lastMessage: "The project deadline is approaching",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    isChannel: false,
  },
  {
    id: "user3",
    name: "Sophia Chen",
    avatar: "/placeholder.svg?height=40&width=40",
    email: "sophia@example.com",
    isOnline: true,
    lastSeen: "Just now",
    lastMessage: "Thanks for your help!",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    isChannel: false,
  },
  {
    id: "user4",
    name: "Michael Johnson",
    avatar: "/placeholder.svg?height=40&width=40",
    email: "michael@example.com",
    isOnline: false,
    lastSeen: "1 day ago",
    lastMessage: "Did you see the latest update?",
    lastMessageTime: "Monday",
    unreadCount: 1,
    isChannel: false,
  },
  {
    id: "user5",
    name: "Olivia Martinez",
    avatar: "/placeholder.svg?height=40&width=40",
    email: "olivia@example.com",
    isOnline: true,
    lastSeen: "Just now",
    lastMessage: "Let's schedule a call next week",
    lastMessageTime: "Monday",
    unreadCount: 0,
    isChannel: false,
  },
]

// Mock channels data
export const mockChannels: Channel[] = [
  {
    id: "channel1",
    name: "Tech News",
    description: "Latest updates from the tech world",
    avatar: "",
    memberCount: 256,
    lastMessageTime: "2 hours ago",
    unreadCount: 5,
    verified: true,
  },
  {
    id: "channel2",
    name: "Design Inspiration",
    description: "Share your design work and get feedback",
    avatar: "",
    memberCount: 128,
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    verified: false,
  },
  {
    id: "channel3",
    name: "Job Opportunities",
    description: "Find your next career move",
    avatar: "",
    memberCount: 512,
    lastMessageTime: "3 days ago",
    unreadCount: 0,
    verified: true,
  },
]

// Mock messages data
export const mockMessages: Message[] = [
  {
    id: "msg1",
    senderId: "user1",
    receiverId: "current-user",
    content: "Hey there! How's your day going?",
    timestamp: "2023-06-15T10:30:00Z",
    status: "read",
  },
  {
    id: "msg2",
    senderId: "current-user",
    receiverId: "user1",
    content: "Pretty good, thanks! Just finishing up some work. How about you?",
    timestamp: "2023-06-15T10:32:00Z",
    status: "read",
  },
  {
    id: "msg3",
    senderId: "user1",
    receiverId: "current-user",
    content: "I'm doing well! I was wondering if you're free to meet up this weekend?",
    timestamp: "2023-06-15T10:35:00Z",
    status: "read",
  },
  {
    id: "msg4",
    senderId: "current-user",
    receiverId: "user1",
    content: "That sounds great! I should be free on Saturday afternoon. What did you have in mind?",
    timestamp: "2023-06-15T10:38:00Z",
    status: "read",
  },
  {
    id: "msg5",
    senderId: "user1",
    receiverId: "current-user",
    content: "I was thinking we could check out that new café downtown. I've heard they have amazing pastries!",
    timestamp: "2023-06-15T10:40:00Z",
    status: "read",
  },
  {
    id: "msg6",
    senderId: "user1",
    receiverId: "current-user",
    content: "Let me know when you're free to meet",
    timestamp: "2023-06-15T10:42:00Z",
    status: "delivered",
  },
  {
    id: "msg7",
    senderId: "user2",
    receiverId: "current-user",
    content: "Hi there, just checking in about the project status. How's everything going?",
    timestamp: "2023-06-14T14:20:00Z",
    status: "read",
  },
  {
    id: "msg8",
    senderId: "current-user",
    receiverId: "user2",
    content: "Hey! Everything's on track. I've completed the first phase and I'm starting on the second now.",
    timestamp: "2023-06-14T14:25:00Z",
    status: "read",
  },
  {
    id: "msg9",
    senderId: "user2",
    receiverId: "current-user",
    content: "That's great to hear! Remember, the project deadline is approaching. Let me know if you need any help.",
    timestamp: "2023-06-14T14:30:00Z",
    status: "delivered",
  },
]
